{% set name = "survey" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/survey-{{ version }}.tar.gz
  sha256: 57034ed4326db01bd0732fe252096e0f4b5ca16dc530c59658f62ab1de0c936e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - survey
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Exahilosys/survey
  summary: A simple library for creating beautiful interactive prompts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
