{% set name = "survey" %}
{% set version = "5.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/survey-{{ version }}.tar.gz
  sha256: e2f9e3b526f0db2fe8f9f4960e5fc2a93119925d2350b18e2d445d6740692af6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - survey
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Exahilosys/survey
  summary: A simple library for creating beautiful interactive prompts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
