{% set name = "survey" %}
{% set version = "5.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/survey-{{ version }}.tar.gz
  sha256: 8cc4edb2b11db7734fcbc35f78d3d7e183708c7da06907cef3d21a83f3014be0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7

test:
  imports:
    - survey
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Exahilosys/survey
  summary: A simple library for creating beautiful interactive prompts.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
